export const MODERATE_ADDITIONAL_CHANNEL_COUNT = 19;
export const MODERATE_TOPIC_COUNT = 500;
export const MODERATE_LONG_TOPIC_MESSAGE_COUNT = 1_001;
export const MODERATE_HIGH_MESSAGE_TOPIC_COUNT = 18;
export const MODERATE_HIGH_MESSAGE_TOPIC_MESSAGE_COUNT = 19;
export const MODERATE_DEFAULT_TOPIC_MESSAGE_COUNT = 18;

export const MODERATE_CHANNEL_COUNT = MODERATE_ADDITIONAL_CHANNEL_COUNT + 1;
export const MODERATE_MESSAGE_COUNT =
  MODERATE_LONG_TOPIC_MESSAGE_COUNT +
  (MODERATE_HIGH_MESSAGE_TOPIC_COUNT - 1) * MODERATE_HIGH_MESSAGE_TOPIC_MESSAGE_COUNT +
  (MODERATE_TOPIC_COUNT - MODERATE_HIGH_MESSAGE_TOPIC_COUNT) * MODERATE_DEFAULT_TOPIC_MESSAGE_COUNT;
export const MODERATE_LONG_TOPIC_REPLY_COUNT = MODERATE_LONG_TOPIC_MESSAGE_COUNT - 1;
