packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@effect/vitest": 4.0.0-beta.98
  "@types/node": ^24
  effect: 4.0.0-beta.98
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  "@prisma/engines": true
  msgpackr-extract: false
  prisma: true
