/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as WorkspaceInvitationsRedeemRouteImport } from './routes/workspace-invitations.redeem'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as WorkspacesWorkspaceIdIndexRouteImport } from './routes/workspaces.$workspaceId.index'
import { Route as WorkspacesWorkspaceIdChannelsChannelIdRouteImport } from './routes/workspaces.$workspaceId.channels.$channelId'
import { Route as WorkspacesWorkspaceIdChannelsChannelIdIndexRouteImport } from './routes/workspaces.$workspaceId.channels.$channelId.index'
import { Route as WorkspacesWorkspaceIdChannelsChannelIdTopicsTopicIdRouteImport } from './routes/workspaces.$workspaceId.channels.$channelId.topics.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceInvitationsRedeemRoute =
  WorkspaceInvitationsRedeemRouteImport.update({
    id: '/workspace-invitations/redeem',
    path: '/workspace-invitations/redeem',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdIndexRoute =
  WorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdChannelsChannelIdRoute =
  WorkspacesWorkspaceIdChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdChannelsChannelIdIndexRoute =
  WorkspacesWorkspaceIdChannelsChannelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdChannelsChannelIdRoute,
  } as any)
const WorkspacesWorkspaceIdChannelsChannelIdTopicsTopicIdRoute =
  WorkspacesWorkspaceIdChannelsChannelIdTopicsTopicIdRouteImport.update({
    id: '/topics/$topicId',
    path: '/topics/$topicId',
    getParentRoute: () => WorkspacesWorkspaceIdChannelsChannelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/workspace-invitations/redeem': typeof WorkspaceInvitationsRedeemRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/channels/$channelId': typeof WorkspacesWorkspaceIdChannelsChannelIdRouteWithChildren
  '/workspaces/$workspaceId/channels/$channelId/': typeof WorkspacesWorkspaceIdChannelsChannelIdIndexRoute
  '/workspaces/$workspaceId/channels/$channelId/topics/$topicId': typeof WorkspacesWorkspaceIdChannelsChannelIdTopicsTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/workspace-invitations/redeem': typeof WorkspaceInvitationsRedeemRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/channels/$channelId': typeof WorkspacesWorkspaceIdChannelsChannelIdIndexRoute
  '/workspaces/$workspaceId/channels/$channelId/topics/$topicId': typeof WorkspacesWorkspaceIdChannelsChannelIdTopicsTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/workspace-invitations/redeem': typeof WorkspaceInvitationsRedeemRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/channels/$channelId': typeof WorkspacesWorkspaceIdChannelsChannelIdRouteWithChildren
  '/workspaces/$workspaceId/channels/$channelId/': typeof WorkspacesWorkspaceIdChannelsChannelIdIndexRoute
  '/workspaces/$workspaceId/channels/$channelId/topics/$topicId': typeof WorkspacesWorkspaceIdChannelsChannelIdTopicsTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/verify'
    | '/workspace-invitations/redeem'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/channels/$channelId'
    | '/workspaces/$workspaceId/channels/$channelId/'
    | '/workspaces/$workspaceId/channels/$channelId/topics/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/verify'
    | '/workspace-invitations/redeem'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/channels/$channelId'
    | '/workspaces/$workspaceId/channels/$channelId/topics/$topicId'
  id:
    | '__root__'
    | '/'
    | '/auth/verify'
    | '/workspace-invitations/redeem'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/channels/$channelId'
    | '/workspaces/$workspaceId/channels/$channelId/'
    | '/workspaces/$workspaceId/channels/$channelId/topics/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  WorkspaceInvitationsRedeemRoute: typeof WorkspaceInvitationsRedeemRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace-invitations/redeem': {
      id: '/workspace-invitations/redeem'
      path: '/workspace-invitations/redeem'
      fullPath: '/workspace-invitations/redeem'
      preLoaderRoute: typeof WorkspaceInvitationsRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/': {
      id: '/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/channels/$channelId': {
      id: '/workspaces/$workspaceId/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/workspaces/$workspaceId/channels/$channelId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdChannelsChannelIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/channels/$channelId/': {
      id: '/workspaces/$workspaceId/channels/$channelId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/channels/$channelId/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdChannelsChannelIdIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdChannelsChannelIdRoute
    }
    '/workspaces/$workspaceId/channels/$channelId/topics/$topicId': {
      id: '/workspaces/$workspaceId/channels/$channelId/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/workspaces/$workspaceId/channels/$channelId/topics/$topicId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdChannelsChannelIdTopicsTopicIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdChannelsChannelIdRoute
    }
  }
}

interface WorkspacesWorkspaceIdChannelsChannelIdRouteChildren {
  WorkspacesWorkspaceIdChannelsChannelIdIndexRoute: typeof WorkspacesWorkspaceIdChannelsChannelIdIndexRoute
  WorkspacesWorkspaceIdChannelsChannelIdTopicsTopicIdRoute: typeof WorkspacesWorkspaceIdChannelsChannelIdTopicsTopicIdRoute
}

const WorkspacesWorkspaceIdChannelsChannelIdRouteChildren: WorkspacesWorkspaceIdChannelsChannelIdRouteChildren =
  {
    WorkspacesWorkspaceIdChannelsChannelIdIndexRoute:
      WorkspacesWorkspaceIdChannelsChannelIdIndexRoute,
    WorkspacesWorkspaceIdChannelsChannelIdTopicsTopicIdRoute:
      WorkspacesWorkspaceIdChannelsChannelIdTopicsTopicIdRoute,
  }

const WorkspacesWorkspaceIdChannelsChannelIdRouteWithChildren =
  WorkspacesWorkspaceIdChannelsChannelIdRoute._addFileChildren(
    WorkspacesWorkspaceIdChannelsChannelIdRouteChildren,
  )

interface WorkspacesWorkspaceIdRouteChildren {
  WorkspacesWorkspaceIdIndexRoute: typeof WorkspacesWorkspaceIdIndexRoute
  WorkspacesWorkspaceIdChannelsChannelIdRoute: typeof WorkspacesWorkspaceIdChannelsChannelIdRouteWithChildren
}

const WorkspacesWorkspaceIdRouteChildren: WorkspacesWorkspaceIdRouteChildren = {
  WorkspacesWorkspaceIdIndexRoute: WorkspacesWorkspaceIdIndexRoute,
  WorkspacesWorkspaceIdChannelsChannelIdRoute:
    WorkspacesWorkspaceIdChannelsChannelIdRouteWithChildren,
}

const WorkspacesWorkspaceIdRouteWithChildren =
  WorkspacesWorkspaceIdRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  WorkspaceInvitationsRedeemRoute: WorkspaceInvitationsRedeemRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
